version: "2.1"

services:
  # https://hub.docker.com/r/homeassistant/home-assistant
  homeassistant:
    image: homeassistant/home-assistant:2024.1.5@sha256:e0cd4f4043f2bdae80224b230cb9ca11e8d15f55f5754148412e32d5af8f98b6
    volumes:
      - config:/config
    ports:
      - "80:80"
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
        #privileged: true
      #    devices:
      #- /dev/ttyAMA0
      #- /dev/ttyS0
      #- /dev/serial0
      #- /dev/serial1

  FiatChamp:
    image: ghcr.io/mathroc/fiatchamp:dev

  # https://hub.docker.com/_/eclipse-mosquitto
  mqtt:
    build: mqtt
    ports:
      - 1883:1883
    volumes:
      - mqtt:/mosquitto/data
    tmpfs:
      - /mosquitto/log

  # https://www.zigbee2mqtt.io/guide/getting-started/#installation
  zigbee2mqtt:
    build: zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
    ports:
      - 7000:7000
    privileged: true
    devices:
      - /dev/ttyAMA0
      - /dev/ttyS0
      - /dev/serial0
      - /dev/serial1
  # - /dev/ttyUSB0:/dev/ttyUSB0

  # https://hub.docker.com/r/codercom/code-server
  code-server:
    image: codercom/code-server:4.92.2@sha256:f32cfa5e7cc768f60969f1d2183fc4c7aa093b80b93c365535e83f79ccf004f2
    command:
      - --port=9000
      - --auth=none
      - --extensions-dir=/config/.vscode
      - --user-data-dir=/config/.vscode
      - /config
    working_dir: /config
    ports:
      - 9000:9000/tcp
    volumes:
      - config:/config
      - zigbee2mqtt:/config/zigbee2mqtt
    user: root

  # https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:1.8.10@sha256:2d4846756ff07787af6cbb62c60d2b130734ed1ffaeab878daeea7fd8dc362d2
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  # https://hub.docker.com/r/grafana/grafana
  grafana:
    image: grafana/grafana:11.2.0@sha256:408afb9726de5122b00a2576763a8a57a3c86d5b0eff5305bc994ceb3eb96c3f
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: homeassistant

volumes:
  config: {}
  influxdb: {}
  grafana: {}
  mqtt: {}
  zigbee2mqtt: {}
